### ISSUE TITLE
Cannot package application to executable file using py2app or Pyinstaller

### ISSUE THREAD

**Issue by REDSoftwareRasmus** [victordomingos/optimize-images-x#2]
I really like this application and it's source code and would very much like to use it for some image optimization projects I am doing together with a small team. Instead of worrying about running the source code directly from the Python project, my intention was to package the application to a distributable, executable file. 

However, when I try to package the installation with py2app or Pyinstaller (I've tried both) I cannot seem to get it to work. I have swept all threads online trying to debug this issue, but I can't find anything. 

I really like your lib @victordomingos! Have you managed to package optimize-images-x to a distributable, executable application? If so, how?

Would really appreciate some insight. 

Thanks in advance!

**Comment by victordomingos** [comment]
Hi! Thanks for your feedback. I intended to package it using one of those tools, but I confess I got a bit stuck in the process. I even made a note to myself (and for anyone who may know how to get it working) in issue #1.

For now, installing with `pip` is still the easiest way.
