### ISSUE TITLE
When executing nothing happens

### ISSUE THREAD

**Issue by NextKool** [victordomingos/optimize-images-x#5]
I have installed the requirements and when executing setup.py nothing happens, I thought it would load an interface like in the example but nothing happens at all. What am I doing wrong?

**Comment by victordomingos** [comment]
The `setup.py` file is not meant to be run directly, but to be used by `pip` instead. The production release is usually installed from PyPI using that command. To install and test he development version directly from GitHub, you can use the `-e` command-line argument. The process is similar to the one briefly described in the user guide for optimize-images:

https://github.com/victordomingos/optimize-images/blob/master/docs/docs_EN.md#installation-and-dependencies

You can also find more details on the documentation for `pip`:

https://packaging.python.org/en/latest/tutorials/installing-packages.html
